export enum Model {
  // 气象数据
  WelcomeWeather = "welcome-weather",
  // 废气废水三联环状图，酸碱废气
  WelcomeAcidGas = "welcome-acid-gas",
  // 废气废水三联环状图，有机废气
  WelcomeOrganicGas = "welcome-organic-gas",
  // 废气废水三联环状图，废水处理
  WelcomeEffluent = "welcome-effluent",
  // 冷热主机三联环状图：冰水主机
  WelcomeIcewaterHost = "welcome-icewater-host",
  // 冷热主机三联环状图：空压机
  WelcomeAcHost = "welcome-ac-host",
  // 冷热主机三联环状图：热泵
  WelcomeHeatPump = "welcome-heat-pump",
  // 冷热水线图
  WelcomeWater = "welcome-water",
  // 冷站能效三坐标环状图
  WelcomeColdStation = "welcome-cold-station",
  // 空压系统三坐标环状图
  WelcomeAcStation = "welcome-ac-station",
  // 耗电量耗水量：日耗电量
  WelcomePowerDaily = "welcome-power-daily",
  // 耗电量耗水量：日耗水量
  WelcomeWaterDaily = "welcome-water-daily",
  // 异常报警数据列表
  WelcomeAlertList = "welcome-alert-list",
  // 供气压力线图
  WelcomePressure = "welcome-pressure",
  // 净化车间温湿度数据列表
  WelcomeTempList = "welcome-temp-list",

  HvacOverviewWeather = "hvac-overview-weather",
  HvacoverviewCategory = "hvac-overview-category",
  HvacOverviewTotal = "hvac-overview-total",
  HvacOverviewWaterTemp = "hvac-overview-water-temp",
  HvacOverviewStationRate = "hvac-overview-station-rate",
  HvacOverviewThermal = "hvac-overview-thermal",
  HvacEmrRmSmColdSource = "hvac-emr-rm-sm-cold-source",
  HvacEmrRmSmDeviceControl = "hvac-emr-rm-sm-device-control",
  HvacEmrRmSmSystemEm = "hvac-emr-rm-sm-system-em",
  HvacEmrMonitorAreaTree = "hvac-emr-monitor-area-tree",
  HvacEmrMonitorHistoryModal = "hvac-emr-monitor-history-modal",
  HvacEmrMonitorHistoryState = "hvac-emr-monitor-history-state",
  HvacEmrMonitorHistoryTime = "hvac-emr-monitor-history-time",
  TmpStationList = "tmp-station-list",
  TmpEnergyCategory = "tmp-energy-category",
  HvacEmrMoniorEaRate = "hvac-emr-monior-ea-rate",
  HvacEmrEaSchedule = "hvac-emr-ea-schedule",
  HvacEmrEaCatetory = "hvac-emr-ea-catetory",
  HvacEmrEaSearch = "hvac-emr-ea-search",
  HvacEmrEaLoad = "hvac-emr-ea-load",
  HvacEmrEaHeatBalance = "hvac-emr-ea-heat-balance",
  HvacEmrEaHeatRate = "hvac-emr-ea-heat-rate",
  HvacEmrColdLog = "hvac-emr-cold-log",
  HvacCacOeConfigure = "hvac-cac-oe-configure",
  HvacCacOeCollection = "hvac-cac-oe-collection",
  HvacCacOeValve = "hvac-cac-oe-valve",
  HvacCacOeTemperature = "hvac-cac-oe-temperature",
  HvacCacCeHumidity = "hvac-cac-ce-humidity",
  HvacCacLdiConfigure = "hvac-cac-ldi-configure",
  HvacCacLdiCollection = "hvac-cac-ldi-collection",
  HvacCacLdiValve = "hvac-cac-ldi-valve",
  HvacCacLdiTemperature = "hvac-cac-ldi-temperature",
  HvacCacLdiHumidity = "hvac-cac-ldi-humidity",
  HvacCacSpeConfigure = "hvac-cac-spe-configure",
  HvacCacSpeCollection = "hvac-cac-spe-collection",
  HvacCacSpeValve = "hvac-cac-spe-valve",
  HvacCacSpeTemperature = "hvac-cac-spe-temperature",
  HvacCacSpeHumidity = "hvac-cac-spe-humidity",
  HvacCacSmeCollection = "hvac-cac-sme-collection",
  HvacCacSmeValve = "hvac-cac-sme-valve",
  HvacCacSmeTemperature = "hvac-cac-sme-temperature",
  HvacCacSmeHumidity = "hvac-cac-sme-humidity",
  HvacCacQtConfigure = "hvac-cac-qt-configure",
  hvacCacQtCollection = "hvac-cac-qt-collection",
  HvacCacQtValve = "hvac-cac-qt-valve",
  HvacCacQtTemperature = "hvac-cac-qt-temperature",
  HvacCacQtHumidity = "hvac-cac-qt-humidity",
  HvacCacSmsCollection = "hvac-cac-sms-collection",
  HvacCacSmsValve = "hvac-cac-sms-valve",
  HvacCacSmsTemperature = "hvac-cac-sms-temperature",
  HvacCacSmsHumidity = "hvac-cac-sms-humidity",
  HvacCacFtConfigure = "hvac-cac-ft-configure",
  HvacCacFtCollection = "hvac-cac-ft-collection",
  HvacCacFtValve = "hvac-cac-ft-valve",
  HvacCacFtTemperature = "hvac-cac-ft-temperature",
  HvacCacFtHumidity = "hvac-cac-ft-humidity",
  ApAprConfigure = "ap-apr-configure",
  ApAprSupplyPresure = "ap-apr-supply-presure",
  ApAprExhaustTemperature = "ap-apr-exhaust-temperature",
  ApAprGasConsumption = "ap-apr-gas-consumption",
  HeatOvConfigure = "heat-ov-configure",
  ElectricEcsCombine = "electric-ecs-combine",
  ElectricEcsLoad = "electric-ecs-load",
  ElectricEcsCurrent = "electric-ecs-current",
  ElectricEcsVoltage = "electric-ecs-voltage",
  ElectricDtDaily = "electric-dt-daily",
  ElectricDtConsumption = "electric-dt-consumption",
  ElectricDtTotal = "electric-dt-total",
  ElectricCategoryAnalysis = "electric-category-analysis",
  ElectricPcaYoy = "electric-pca-yoy",
  ElectricPcaMom = "electric-pca-mom",
  ElectricPcaCollection = "electric-pca-collection",
  ElectricPcaCustom = "electric-pca-custom",
  ElectricPcaUti = "electric-pca-uti",
}
